### ISSUE TITLE
Allow querying for the preload status of a domain, taking into account ancestor domains.

### ISSUE THREAD

**Issue by lgarron** [chromium/hstspreload#85]
From https://github.com/chromium/hstspreload.appspot.com/issues/52

Strawman: introduce a new status for this (but don't use it in the database).

**Comment by marumari** [comment]
This is tricky to do on my under, because it can sometimes be surprisingly complicated to find the second-level domain of something.  In my own code, I just take the easy route and walk up the ladder:

https://github.com/mozilla/http-observatory/blob/master/httpobs/scanner/analyzer/utils.py#L75

To do it in JS, I'd either need to integrate the Public Suffix List (ugh for such a small thing), or make a whole bunch of calls to the hstspreload API, walking up the domain chain.

**Comment by lgarron** [comment]
I will be traveling a bunch, and this is unlikely to be important for me to handle until August.

If you want to have a go at this, I would suggest modifying [`
func (idx IndexedEntries) Get(domain string) (Entry, bool)`](https://github.com/chromium/hstspreload/blob/afa93be1c8b10bb81093138132f4873a5b4f08e0/chromium/preloadlist/preloadlist.go#L68) to:
- return an enum instead of a bool: not found, exact entry found, ancestor entry found
- for "ancestor domain found", pass back the matching ancestor entry

**Comment by jianglai** [comment]
@ericlaw1979 Can you close this issue?
